# Generated by Django 5.2.4 on 2025-08-02 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('max_players', models.IntegerField(default=6)),
                ('current_round', models.IntegerField(default=0)),
                ('pot', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chips', models.IntegerField(default=1000)),
                ('position', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('current_bet', models.IntegerField(default=0)),
                ('hand_cards', models.TextField(default='[]')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('phase', models.CharField(choices=[('preflop', 'Pre-flop'), ('flop', 'Flop'), ('turn', 'Turn'), ('river', 'River'), ('showdown', 'Showdown')], default='preflop', max_length=20)),
                ('community_cards', models.TextField(default='[]')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.game')),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poker.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('fold', 'Fold'), ('check', 'Check'), ('call', 'Call'), ('raise', 'Raise'), ('all_in', 'All In')], max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.gameround')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.player')),
            ],
        ),
    ]
