# Generated by Django 5.2.4 on 2025-08-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_game_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
    ]
