# Generated by Django 5.2.4 on 2025-08-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_player_is_ai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameround',
            name='current_player',
        ),
        migrations.AddField(
            model_name='game',
            name='dealer_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='deck_cards',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='current_player_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='highest_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='is_betting_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='has_acted_this_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_folded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='phase',
            field=models.CharField(choices=[('preflop', 'Pre-flop'), ('flop', 'Flop'), ('turn', 'Turn'), ('river', 'River'), ('showdown', 'Showdown'), ('finished', 'Finished')], default='preflop', max_length=20),
        ),
    ]
