# Generated by Django 5.2.4 on 2025-08-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0004_remove_gameround_current_player_game_dealer_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='big_blind',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='game',
            name='small_blind',
            field=models.IntegerField(default=10),
        ),
    ]
